'use client';

import { useState } from 'react';
import { useParams } from 'next/navigation';
import { fmtDateTime } from '@/lib/format';
import { ModuleGuard, PageHeader, PageIntro } from '@/lib/ui';
import { LorryReceipt, TripDetail } from '../../types';
import { TripTabs } from '../tabs';
import { LorryReceiptContent } from './content';

/**
 * Lorry receipt — `/trips/[id]/lr` (part 05 §5).
 *
 * One record per trip: the LR and the E-LR are the same document, held once
 * (BR-22). `Generate LR` consumes the number inside the issuing transaction
 * and is blocked before the truck is placed (BR-13) and while any cross-check
 * mismatch is open (BR-32). Sharing is optional, always.
 *
 * The actual fill-in/autosave/generate/share workflow lives in
 * `LorryReceiptContent` (`./content.tsx`) — this route wraps it in this
 * page's own header and tab strip, mirrored from the content's `onLoaded`
 * callback rather than fetched a second time, so the order detail page's
 * Documents tab can embed the identical, fully working thing.
 */
export default function LorryReceiptPage() {
  const { id } = useParams<{ id: string }>();
  const [data, setData] = useState<{ trip: TripDetail; lr: LorryReceipt } | null>(null);

  return (
    <ModuleGuard module="trips">
      {data ? (
        <PageHeader
          path={`/trips/${id}/lr`}
          title={data.lr.code ?? 'Lorry receipt — draft'}
          sub={
            data.lr.code
              ? `${data.lr.status.replace(/_/g, ' ').toLowerCase()} · issued ${fmtDateTime(data.lr.bookedAt)}`
              : 'Autosaves every three seconds'
          }
          module="trips"
        />
      ) : (
        <PageHeader path={`/trips/${id}/lr`} title="Lorry receipt" module="trips" />
      )}
      <PageIntro
        what="Fill in and generate this trip's lorry receipt — generating it locks the form, and is blocked until the truck is placed and any cross-check mismatch is resolved."
        who="Generated by operations; sharing with the transporter is optional."
      />
      <TripTabs tripId={id} />

      <LorryReceiptContent tripId={id} onLoaded={setData} />
    </ModuleGuard>
  );
}
